const $=s=>document.querySelector(s);const screen=$('#screen');
const store=JSON.parse(localStorage.getItem('jishoMaster')||'{}');
const state={mode:null,step:0,level:1,words:[],selected:null,bookWord:'たんぽぽ',bookPage:0,challenge:false,time:60,correct:0,miss:0,combo:0,bestCombo:0,timer:null};
const save=()=>{const before=state.lastXP??(store.xp||0);const after=store.xp||0;if(after>before&&typeof checkXPBadge==='function')checkXPBadge(before,after);state.lastXP=after;localStorage.setItem('jishoMaster',JSON.stringify(store));updateHeader();if(state.pendingAward)setTimeout(showBadgeAward,750)};const updateHeader=()=>{$('#headerRank').textContent=store.xp>=500?'じしょマスター':store.xp>=200?'名人見習い':'見習い';$('#headerScore').textContent=(store.xp||0)+' XP'};state.lastXP=store.xp||0;updateHeader();
const esc=s=>s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));const NAVI_BASE='https://tt-sensei.github.io/navi-character-/assets/web/characters/';
const naviCharacters=['sora','kai','nami','riku','saku','tsuki'];
const navi=(kind='hint',message='')=>{const character=naviCharacters[(state.naviIndex=(state.naviIndex||0)+1)%naviCharacters.length];const file={greeting:'waving',hint:'hint',correct:'correct',retry:'retry',complete:'complete'}[kind]||'hint';return '<div class="navi-note"><img src="'+NAVI_BASE+character+'/fullbody/'+file+'.webp" alt="" loading="lazy"><span>'+esc(message)+'</span></div>'};
const naviAdvice=()=>{const lines=['まずは「つめ」で、最初の音を見つけよう！','同じ文字なら、次の文字をくらべれば大丈夫。','まちがえても大丈夫。手がかりを一つ戻ればOK！','はしらは、ページの住所みたいなものだよ。','ことばの順番には、ちゃんと理由があるよ。','一問ずつで大丈夫。じっくり見てみよう！'];return lines[(state.adviceIndex=(state.adviceIndex||0)+1)%lines.length]};
const homeNavi=()=>`<div class="navi-home">${[['greeting','ことばの世界へ、ようこそ！'],['hint','「つめ」と「はしら」を使ってみよう。'],['correct','できるところから、気軽に挑戦しよう！']].map(x=>navi(x[0],x[1])).join('')}</div>`;

const home=()=>{clearInterval(state.timer);state.mode=null;screen.innerHTML=`<section class="hero"><div class="eyebrow">ことばを見つける・くらべる・ならべる</div><h1>じしょマスター</h1><p>国語辞典のひみつを、遊びながら身につけよう。</p></section><section class="mode-grid"><button class="mode-card book" data-action="book"><div class="mode-icon">📖</div><h2>じしょをひこう！</h2><p>「つめ」と「はしら」を使って、ことばを見つけよう！</p><span class="go">ひいてみる →</span></button><button class="mode-card words" data-action="words"><div class="mode-icon">🔤</div><h2>ことばならべ！</h2><p>練習しながら、五十音順のルールを確認しよう！</p><span class="go">ルールを学ぶ →</span></button><button class="mode-card challenge" data-action="challenge"><div class="mode-icon">⏱</div><h2>60秒チャレンジ</h2><p>3つのことばを次々に並べて、記録に挑戦しよう！</p><span class="go">チャレンジする →</span></button></section><div class="mini-grid"><button class="small-action" data-action="badges">🏅 バッジルーム</button><button class="small-action" data-action="help">？ あそびかた</button><button class="small-action" data-action="records">★ きろく</button><button class="small-action" data-action="weak">にがてれんしゅう</button></div>${homeNavi()}`};
const header=(title,sub='')=>`<div class="screen-head"><button class="back" data-action="home">← ホーム</button><div><h2>${title}</h2>${sub?`<div class="eyebrow">${sub}</div>`:''}</div><div></div></div><div class="header-navi">${navi('hint',naviAdvice())}</div>`;
function book(){state.mode='book';state.step=1;state.bookPage=0;renderBook()}
const pillarExamples=[['たいいく','たから','たまご','たんす'],['たこ','たね','たぬき','たまご'],['たからもの','たき','たけのこ','たまご'],['たすける','たたかう','たちばな','たてもの'],['たび','たまねぎ','たましい','たんじょうび']];
function dict(hot='',first='たから',last='たまご'){const examples=pillarExamples[(state.bookPage+state.step)%pillarExamples.length];return `<div class="dictionary"><div class="dict-page"><div class="dict-header ${hot==='pillar'?'hot':''}"><span>はしら</span><b>${first}　｜　${last}</b><span>はしら</span></div><div class="dict-columns">${examples.map((word,i)=>`<div class="dict-column"><span class="dict-kana">た</span>${word.slice(1)}</div>`).join('')}</div>${state.bookPage>=2?'<div class="dict-word">たんぽぽ</div>':''}</div><div class="dict-nail ${hot==='nail'?'hot':''}"><b>つめ</b><span>た</span><span>ち</span><span>つ</span><span>て</span><span>と</span></div></div>`}
const bookGuide=()=>`<div class="book-guide" aria-label="辞書をひく手順">${[['つめ','最初の音'],['行','どの行？'],['はしら','範囲を確認'],['本文','見つける']].map((x,i)=>`<span class="${state.step===i+1?'active':''}"><b>${i+1}</b>${x[0]}<small>${x[1]}</small></span>`).join('')}</div>`;
function renderBook(){let content='';if(state.step===1)content=`<div class="mission">「たんぽぽ」を国語辞典で見つけよう！</div>${dict('')}<div class="hint-box"><p>まず、どこを手がかりにする？</p><div class="choices"><button class="choice" data-book="nail">つめ</button><button class="choice" data-book="pillar">はしら</button><button class="choice" data-book="body">本文</button></div><div class="feedback" id="fb"></div></div>`;if(state.step===2)content=`<div class="mission">「た」は何行？</div>${dict('nail')}<div class="choices">${['あ行','か行','さ行','た行','な行','は行'].map(x=>`<button class="choice" data-row="${x}">${x}</button>`).join('')}</div><div class="feedback" id="fb"></div>`;if(state.step===3)content=`<div class="mission">近くまで来たよ。次はどこを見る？</div>${dict('pillar','たから','たまご')}<div class="hint-box"><div class="choices"><button class="choice" data-pillar="nail">つめ</button><button class="choice" data-pillar="pillar">はしら</button><button class="choice" data-pillar="body">本文</button></div><div class="feedback" id="fb"></div></div>`;if(state.step===4)content=`<div class="mission">「たんぽぽ」は、このページにありそう？</div>${dict('pillar','たから','たまご')}<div class="choices"><button class="choice" data-page="yes">ありそう</button><button class="choice" data-page="no">なさそう</button></div><div class="feedback" id="fb"></div>`;if(state.step===5)content=`<div class="mission">「たんぽぽ」は、このページにありそう？</div>${dict('pillar','たんす','ちから')}<div class="choices"><button class="choice" data-page="yes2">ありそう</button><button class="choice" data-page="no2">なさそう</button></div><div class="feedback" id="fb"></div>`;if(state.step===6)content=`<div class="mission pop">📖 パラパラパラ……</div>${dict('pillar','たんす','ちから')}<div class="compare"><div class="answer-title">✨ たんぽぽ、発見！</div><p>つめで場所をさがして、はしらでページをしぼれたね。</p><button class="primary" data-action="bookClear">次のミッションへ</button></div>`;screen.innerHTML=header('じしょをひこう！','LEVEL '+Math.min(state.step,6))+'<div class="progress"><span style="width:${state.step/6*100}%"></span></div>'+bookGuide()+content}
const bookFeedback=(ok,msg,next)=>{const f=$('#fb');f.textContent=msg;f.className='feedback '+(ok?'ok':'no');if(ok)setTimeout(()=>{state.step=next;renderBook()},650)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(a==='home')home();if(a==='help')help();if(a==='records')records();if(a==='weak')weak();if(a==='badges')badges();if(a==='book')book();if(a==='words')words();if(a==='challenge')challenge();if(b.dataset.badgeTab)renderBadges(b.dataset.badgeTab);if(a==='bookClear'){store.xp=(store.xp||0)+50;store.bookClear=true;save();home()}if(b.dataset.book)bookFeedback(b.dataset.book==='nail',b.dataset.book==='nail'?'つめ！ ことばの最初の文字を手がかりに、だいたいの場所をさがすよ。':'ここでは「つめ」を見るよ。',2);if(b.dataset.row)bookFeedback(b.dataset.row==='た行',b.dataset.row==='た行'?'た行！ 辞書が「た」の近くまで移動するよ。':'「た」は、た行だね。',3);if(b.dataset.pillar)bookFeedback(b.dataset.pillar==='pillar',b.dataset.pillar==='pillar'?'はしら！ そのページの最初と最後のことばが分かるよ。':'上の「はしら」を見てみよう。',4);if(b.dataset.page)bookFeedback(b.dataset.page==='no',b.dataset.page==='なさそう！ はしらの範囲に「たんぽぽ」はないね。',5);if(b.dataset.page==='yes2')bookFeedback(true,'ありそう！ ページをめくってみよう。',6);if(b.dataset.page==='no2')bookFeedback(false,'はしらを見ると、「たんぽぽ」はこの中にありそう。',5);if(b.dataset.word)state.challenge?pickChallenge(Number(b.dataset.word)):pick(Number(b.dataset.word));if(b.dataset.decide)state.challenge?challengeDecide():decide()});
const pools=[['いぬ','さる','ねこ'],['あさひ','いちご','うさぎ'],['かさ','かに','かめ'],['たこ','たね','たまご'],['はな','はんこ','はね'],['がっこう','かばん','きっぷ'],['きゅうり','きょうしつ','きょだい'],['ケーキ','けしごむ','けんだま'],['ぶどう','ふうせん','ふで'],['まくら','みかん','むし'],['しんぶん','じてんしゃ','しお'],['てぶくろ','でんしゃ','てんき'],['おちゃ','おと','おに'],['すいか','ずこう','すずめ'],['ぱん','はさみ','ばす'],['りんご','らっぱ','るすばん'],['えんぴつ','おうさま','おりがみ'],['くも','くるま','くつ']];
const levelPoolsData=[
  [['いぬ','さる','ねこ'],['あさひ','いちご','うさぎ'],['えんぴつ','おうさま','かめ'],['くも','さかな','とけい'],['すいか','たまご','はな'],['ふね','まくら','りんご'],['おにぎり','きつね','もも'],['ぞう','でんしゃ','やま']],
  [['かさ','かに','かめ'],['はな','はんこ','はね'],['たこ','たね','たまご'],['まくら','まつり','まど'],['さかな','さくら','さとう'],['ふね','ふで','ふく'],['やさい','やかん','やま'],['りす','りんご','りぼん']],
  [['かい','かいだん','かいもの'],['たまご','たまねぎ','たましい'],['はる','はるかぜ','はるまき'],['ふゆ','ふゆやすみ','ふゆごもり'],['くつ','くつした','くつばこ'],['あめ','あめだま','あめふり'],['そら','そらいろ','そらまめ'],['やま','やまびこ','やまみち']],
  [['たんぽぽ','たんてい','たんじょうび'],['しんぶん','しんごう','しんせつ'],['こうえん','こうさく','こうちゃ'],['はるかぜ','はるまき','はるやすみ'],['おおきい','おおかみ','おおそうじ'],['きょうしつ','きょうりゅう','きょうそう'],['せんせい','せんたく','せんろ'],['でんしゃ','でんちゅう','でんわ']],
  [['かき','がき','かぎ'],['はこ','ばこ','ぱこ'],['はなび','はんこ','ぱんだ'],['てがみ','でんき','てんき'],['さる','ざる','さら'],['ふね','ぶね','ぶどう'],['こま','ごま','こまつな'],['すいか','すいがら','ずこう']],
  [['がっこう','がっき','がっちり'],['きって','きつね','きてん'],['さっか','さかな','さかみち'],['まっすぐ','まつり','まど'],['けっこん','けもの','けしごむ'],['いっぱい','いぬ','いもうと'],['こっぷ','ことり','こま'],['ずっと','ずぼん','すずめ']],
  [['きゃべつ','きゅうり','きょうしつ'],['しゃしん','しゅくだい','しょうがくせい'],['ちゃわん','ちゅうしゃ','ちょうちょ'],['にゃんこ','にゅうがく','にょうぼう'],['ひゃく','ひゅうひゅう','ひょう'],['りゃくご','りゅう','りょうり'],['じゃんけん','じゅぎょう','じょうず'],['みゃく','みゅうじっく','みょうじ']],
  [['ケーキ','ケース','ケーブル'],['コート','コーン','コーナー'],['ジュース','スープ','スーツ'],['ボール','ボタン','ボート'],['チーズ','チーム','チーター'],['ノート','ノコギリ','ノートパソコン'],['カード','カーテン','カーブ'],['セーター','セール','センサー']],
  [['がっこう','きょうしつ','ケーキ'],['ちゃわん','でんしゃ','ぱんだ'],['しんぶん','ずこう','りんご'],['きゅうり','チーズ','つめ'],['はるまき','びょういん','ふうせん'],['こうえん','ざぶとん','しょうぼうしゃ'],['まくら','りょうり','わたあめ'],['けんだま','サッカー','たんぽぽ']],
  [['あさひ','いっぽ','うさぎ'],['かいだん','がっこう','きょうしつ'],['さくら','しゃしん','しゅくだい'],['たまご','だんご','ちょうちょ'],['にんじん','にゅうがく','ねんど'],['はんぶん','ぱんだ','ひこうき'],['ふうせん','ぶどう','プール'],['りんご','りゅう','ルビー']]
];
const kanaOrder='ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぷふへべぺほぼぽまみむめもゃやゅゆょよらりるれろわをんー'.split('');
const kanaVowel={};
[['あ','ぁ','か','が','さ','ざ','た','だ','な','は','ば','ぱ','ま','や','ゃ','ら','わ'],['い','ぃ','き','ぎ','し','じ','ち','ぢ','に','ひ','び','ぴ','み','り'],['う','ぅ','く','ぐ','す','ず','つ','づ','ぬ','ふ','ぶ','ぷ','む','ゆ','ゅ','る'],['え','ぇ','け','げ','せ','ぜ','て','で','ね','へ','べ','ぺ','め','れ'],['お','ぉ','こ','ご','そ','ぞ','と','ど','の','ほ','ぼ','ぽ','も','よ','ょ','ろ','を']].forEach((row,i)=>row.forEach(c=>kanaVowel[c]='あいうえお'[i]));
const kanaBase=c=>{let n=c.normalize('NFD').replace(/[\u3099\u309A]/g,'');if(n>='\u30A1'&&n<='\u30F6')n=String.fromCharCode(n.charCodeAt(0)-0x60);return n};
const kanaVariant=c=>{const n=c.normalize('NFD');return n.includes('\u309A')?2:n.includes('\u3099')?1:0};
const compareTokens=w=>{let previous='';return [...w].map(c=>{const base=kanaBase(c);if(base==='ー'){const vowel=kanaVowel[previous]||'ー';previous=vowel;return {base:vowel,kind:3}}previous=base;return {base,kind:kanaVariant(c)}})};
const dictionaryCompare=(a,b)=>{const aa=compareTokens(a),bb=compareTokens(b),ap=aa.map(t=>kanaOrder.indexOf(t.base)),bp=bb.map(t=>kanaOrder.indexOf(t.base));for(let i=0;i<Math.min(ap.length,bp.length);i++){if(ap[i]!==bp[i])return ap[i]-bp[i]}if(ap.length!==bp.length)return ap.length-bp.length;for(let i=0;i<aa.length;i++){if(aa[i].kind!==bb[i].kind)return aa[i].kind-bb[i].kind}return 0};
function newWords(){const level=Math.min(10,Math.max(1,state.level||1));const pool=levelPoolsData[level-1]||levelPoolsData[0];const source=pool[Math.floor(Math.random()*pool.length)];state.words=[...source].sort(()=>Math.random()-.5);state.selected=null}
function words(){state.mode='words';state.level=Number(store.wordLevel||1);state.challenge=false;newWords();renderWords()}
function renderWords(){screen.innerHTML=header('ことばならべ！','LEVEL '+state.level+' ／ ルール確認')+`<p class="mission">じしょに出てくる順に、<b>1・2・3</b>とならべよう！</p><div class="rule-strip"><span>① 前から見る</span><span>② 同じなら次へ</span><span>③ 違う文字で決まる</span></div><div class="panel"><div class="word-cards">${state.words.map((w,i)=>`<button class="word-card ${state.selected===i?'selected':''}" data-word="${i}"><span class="position-number">${i+1}</span>${esc(w)}</button>`).join('')}</div><p class="center explain">カードを2つタップすると、場所が入れかわるよ。</p><div class="center"><button class="primary gold" data-decide="1">これで決定！</button></div><div id="wordFeedback" class="feedback"></div></div><div class="mini-grid"><button class="small-action" data-action="home">ホームへ</button></div>`}
function pick(i){playSound('click');if(state.selected===null){state.selected=i}else if(state.selected!==i){[state.words[state.selected],state.words[i]]=[state.words[i],state.words[state.selected]];state.selected=null}renderWords()}
function pickChallenge(i){playSound('click');if(state.selected===null){state.selected=i}else if(state.selected!==i){[state.words[state.selected],state.words[i]]=[state.words[i],state.words[state.selected]];state.selected=null}renderChallenge()}
function decide(){const good=state.words.every((w,i)=>i===0||dictionaryCompare(state.words[i-1],w)<=0);const f=$('#wordFeedback');if(good){playSound('correct');store.xp=(store.xp||0)+10;store.wordCorrect=(store.wordCorrect||0)+1;store.wordLevel=Math.min(10,(store.wordLevel||1)+1);save();f.textContent='✨ せいかい！';f.className='feedback ok';setTimeout(()=>renderCompare(),500)}else{playSound('near');store.wordMiss=(store.wordMiss||0)+1;store.weakRule=store.weakRule||'文字のくらべ方';save();f.textContent='おしい！ 前から一文字ずつくらべてみよう。';f.className='feedback no';setTimeout(()=>renderCompare(),550)}}
function renderCompare(){const sorted=[...state.words].sort(dictionaryCompare);screen.innerHTML=header('どこで決まった？','ことばならべ')+`<div class="panel"><div class="compare"><h3>前から一文字ずつ見る</h3><div class="compare-words">${sorted.map((w,i)=>`<div class="compare-word">${[...w].map((c,j)=>j===0?`<mark>${c}</mark>`:c).join('')}</div>`).join('')}</div><p>まず清音・濁音を同じ仲間として比べ、同じ形なら清音を先にするよ。</p><strong>${sorted.join(' → ')}</strong></div><div class="center"><button class="primary" data-action="words">もう一問</button><button class="secondary" data-action="home">ホームへ</button></div></div>`}
function challenge(){playSound('start');state.challenge=true;state.time=60;state.correct=0;state.miss=0;state.combo=0;state.bestCombo=0;newWords();renderChallenge();state.timer=setInterval(()=>{state.time--;if(state.time===10)playSound('alarm');renderChallenge();if(state.time<=0){clearInterval(state.timer);playSound('gameover');renderResult()}},1000)}
function renderChallenge(){screen.innerHTML=header('60秒チャレンジ','ことばならべ')+`<div class="panel center ${state.challengeFlash?'challenge-success-panel':''}"><div class="challenge-time">残り ${state.time} 秒　｜　<span class="combo-count">${state.combo} COMBO</span></div>${state.challengeFlash?`<div class="challenge-flash">✨ せいかい！ <span>${state.combo} COMBO</span></div>`:''}<p class="mission">じしょに出てくる順に、<b>1・2・3</b>とならべよう！</p><div class="word-cards">${state.words.map((w,i)=>`<button class="word-card ${state.selected===i?'selected':''}" data-word="${i}"><span class="position-number">${i+1}</span>${esc(w)}</button>`).join('')}</div><button class="primary gold" data-decide="challenge">決定！</button><div class="feedback">正解 ${state.correct}問　まちがい ${state.miss}問</div></div>`}
function challengeDecide(){const good=state.words.every((w,i)=>i===0||key(state.words[i-1])<=key(w));if(good){state.correct++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.challengeFlash=true;playSound('combo',state.combo)}else{state.miss++;state.combo=0;state.challengeFlash=false;playSound('wrong')}state.selected=null;newWords();renderChallenge();if(good)setTimeout(()=>{state.challengeFlash=false;renderChallenge()},650)}
function renderResult(){const total=state.correct+state.miss;const rate=total?Math.round(state.correct/total*100):0;store.best=Math.max(store.best||0,state.correct);store.challengeCorrect=(store.challengeCorrect||0)+state.correct;store.challengeBestCombo=Math.max(store.challengeBestCombo||0,state.bestCombo);save();screen.innerHTML=header('RESULT','60秒チャレンジ')+`<div class="panel records-card center"><div class="stats"><div class="stat"><strong>${state.correct}</strong>正解</div><div class="stat"><strong>${state.miss}</strong>まちがい</div><div class="stat"><strong>${rate}%</strong>正答率</div><div class="stat"><strong>${state.bestCombo}</strong>最高コンボ</div></div><p class="eyebrow">BEST ${store.best||0}問　｜　累計 ${store.challengeCorrect||0}問</p><button class="primary" data-action="words">もう一度</button><button class="secondary" data-action="home">ホームへ</button></div>`}
const BADGE_BASE='https://tt-sensei.github.io/edu-assets/';
const badgeTabs={common:{label:'共通',icon:'🌟'},japanese:{label:'国語',icon:'📚'},levels:{label:'ことばレベル',icon:'🔤'},challenge:{label:'チャレンジ',icon:'⏱'},elements:{label:'エレメント',icon:'✨'},collections:{label:'コレクション',icon:'🧩'}};
const badgeData={
 common:[['first-step','はじめの一歩','学習を始めた',10],['great-answer','ナイスアンサー','問題に正解した',20],['keep-going','継続パワー','何度も学習した',50],['level-up','レベルアップ','ことばならべのレベルが上がった',70],['combo','コンボ','連続正解に挑戦した',90],['discovery','発見','新しいことに気づいた',120],['try-again','もういちど！','まちがいから再挑戦した',140],['deep-thinker','じっくり思考','理由を考えて答えた',170],['independent','じぶんでできた','自分の力でやり遂げた',220],['hidden-badge','ひみつのバッジ','特別な条件を達成した',300]],
 japanese:[['word-sprout','ことのはの芽','新しい言葉を知った',10],['bookmark','読みすすめた！','文章や本を読み進めた',20],['word-weaver','ことばの紡ぎ手','言葉や文をつないだ',40],['word-detective','ことば探偵','表現や手がかりに気づいた',70],['reading-aloud','音読マスター','声に出してしっかり読んだ',100],['language-explorer','日本語たんけん','言葉や文の仕組みを調べた',150],['words-connect','ことばの架け橋','考えや気持ちを言葉で伝えた',220]],
 elements:[['fire','炎'],['water','水'],['nature','自然'],['thunder','雷'],['ice','氷'],['wind','風'],['earth','大地'],['light','光'],['moon','月'],['crystal','結晶'],['shadow','影'],['gravity','重力'],['cosmos','宇宙'],['sound','音'],['rainbow','虹'],['dream','夢'],['bubble','泡'],['cloud','雲'],['flower','花'],['fairy','妖精'],['candy','キャンディ'],['rain','雨']].map((x,i)=>[x[0],x[1],`${x[1]}のエレメント`,40+i*12]),
 levels:[['first-step','LEVEL 1 はじめの一歩','1文字目が違う問題をクリア',1],['level-up','LEVEL 2 くらべ名人','1文字目が同じ問題をクリア',2],['growth','LEVEL 3 ことばの先へ','2文字目まで同じ問題をクリア',3],['new-skill','LEVEL 4 じっくり比較','3文字目以降を比べる問題をクリア',4],['keep-going','LEVEL 5 にごりもOK','濁音・半濁音を含む問題をクリア',5],['try-again','LEVEL 6 ちいさい「っ」','促音を含む問題をクリア',6],['explorer','LEVEL 7 や・ゆ・よ','拗音を含む問題をクリア',7],['speed','LEVEL 8 のばす音','長音を含む問題をクリア',8],['combo','LEVEL 9 ミックス','いろいろな問題をクリア',9],['mastery','LEVEL 10 じしょマスター','最高レベルに到達',10]],
 challenge:[['speed','スピードスター','60秒チャレンジで1問正解',1],['combo','チャレンジコンボ','最高コンボ3を達成',3],['accuracy','正確無比','60秒チャレンジ累計10問正解',10],['champion','チャレンジチャンピオン','60秒チャレンジ累計25問正解',25],['special','60秒の達人','最高コンボ7を達成',7]],
 collections:[['animal','ANIMAL','どうぶつ',60],['fruit','FRUIT','フルーツ',90],['sea-animal','SEA ANIMAL','海のなかま',120],['dinosaur','DINOSAUR','きょうりゅう',150],['gem','GEM','ジェム',180],['fantasy','FANTASY','ファンタジー',230]]
};
function checkXPBadge(before,after){for(const [tab,items] of Object.entries(badgeData)){if(['levels','challenge'].includes(tab))continue;const item=items.find(x=>before<x[3]&&after>=x[3]);if(item){state.pendingAward={tab,title:item[1],description:item[2],slug:item[0]};break}}}
function showBadgeAward(){if(!state.pendingAward)return;const a=state.pendingAward;const image=a.tab==='elements'?`${BADGE_BASE}assets/elements/${a.slug}/level-1/badge.png`:a.tab==='collections'?`${BADGE_BASE}assets/collections/${a.slug}/common/${a.slug==='animal'?'bear':a.slug==='fruit'?'apple':a.slug==='sea-animal'?'clownfish':a.slug==='dinosaur'?'ankylosaurus':a.slug==='gem'?'amethyst':'dragon'}/badge.png`:`${BADGE_BASE}assets/badges/${a.tab==='japanese'?'japanese':'common'}/${a.slug}/badge.png`;const el=document.createElement('div');el.className='award-backdrop';el.innerHTML=`<div class="award-card" role="dialog" aria-label="バッジ獲得"><div class="award-spark">✦</div><div class="award-label">BADGE GET!</div><img src="${image}" alt="${a.title}"><h2>🏅 ${a.title}</h2><p>${a.description}</p><button class="primary" data-close-award>コレクションに追加！</button></div>`;document.body.appendChild(el);playSound('badge');state.pendingAward=null}
function badgeUnlocked(tab,item){if(tab==='levels')return (store.wordLevel||1)>=item[3];if(tab==='challenge'){if(item[0]==='speed')return (store.challengeCorrect||0)>=1;if(item[0]==='combo'||item[0]==='special')return (store.challengeBestCombo||0)>=item[3];return (store.challengeCorrect||0)>=item[3]}if(tab==='elements'||tab==='collections')return (store.xp||0)>=item[3];return (store.xp||0)>=item[3]}
function badgeImage(tab,slug,level){if(['common','japanese','levels','challenge'].includes(tab))return `${BADGE_BASE}assets/badges/${tab==='japanese'?'japanese':'common'}/${slug}/badge.png`;if(tab==='elements')return `${BADGE_BASE}assets/elements/${slug}/${level}/badge.png`;return `${BADGE_BASE}assets/collections/${slug}/common/${level}/badge.png`}
function renderBadges(tab='common'){state.badgeTab=tab;const data=badgeData[tab];const cards=data.map(item=>{const slug=item[0],unlocked=badgeUnlocked(tab,item),level=tab==='elements'?(store.xp>=item[3]+35?'level-3':store.xp>=item[3]+15?'level-2':'level-1'):'badge';let src=tab==='collections'?`${BADGE_BASE}assets/collections/${slug}/common/${slug==='animal'?'bear':slug==='fruit'?'apple':slug==='sea-animal'?'clownfish':slug==='dinosaur'?'ankylosaurus':slug==='gem'?'amethyst':'dragon'}/badge.png`:badgeImage(tab,slug,level);return `<article class="badge-card ${unlocked?'unlocked':'locked'}"><div class="badge-image-wrap"><img src="${src}" alt="${item[1]}" loading="lazy"></div><div class="badge-card-title">${unlocked?'':'🔒 '}${item[1]}</div><p>${item[2]||'コレクション'}</p>${tab==='elements'?`<span class="badge-level">${level.replace('level-','Lv.')}</span>`:''}</article>`}).join('');screen.innerHTML=header('バッジルーム','学びのコレクション')+`<div class="badge-intro"><strong>学習すると、バッジやエレメントが解放されるよ。</strong><span>${store.xp||0} XP</span></div><div class="badge-tabs">${Object.entries(badgeTabs).map(([key,x])=>`<button class="badge-tab ${key===tab?'active':''}" data-badge-tab="${key}">${x.icon} ${x.label}</button>`).join('')}</div><div class="badge-grid">${cards}</div><div class="center"><button class="secondary" data-action="home">ホームへ</button></div>`}
function badges(){renderBadges('common')}
function weak(){screen.innerHTML=header('にがてれんしゅう')+`<div class="panel records-card center"><h3>覚えておきたいルール</h3><div class="rule-tags"><span class="tag">${store.weakRule||'まずは一文字目'}</span><span class="tag">同じなら次の文字</span><span class="tag">濁音・半濁音</span><span class="tag">小さい「っ」</span><span class="tag">長音「ー」</span></div><p>まちがえたルールを優先して出題するよ。</p><button class="primary" data-action="words">練習を始める</button></div>`}
function help(){screen.innerHTML=header('あそびかた')+`<div class="panel records-card"><h3>📖 じしょをひこう！</h3><p><b>つめ</b>で、ことばの最初の文字の場所をさがすよ。</p><p><b>はしら</b>で、そのページのことばの範囲をたしかめるよ。</p><hr><h3>🔤 ことばならべ！</h3><p>ことばを前から一文字ずつ見て、同じなら次の文字をくらべよう。</p><p class="center"><button class="primary" data-action="home">わかった！</button></p></div>`}home();
document.addEventListener('click',e=>{const b=e.target.closest('[data-close-award]');if(b)b.closest('.award-backdrop')?.remove()});
