const $=s=>document.querySelector(s);const screen=$('#screen');
const store=JSON.parse(localStorage.getItem('jishoMaster')||'{}');
const state={mode:null,step:0,level:1,words:[],selected:null,bookWord:'たんぽぽ',bookPage:0,challenge:false,time:60,correct:0,miss:0,combo:0,bestCombo:0,timer:null};
const save=()=>{localStorage.setItem('jishoMaster',JSON.stringify(store));updateHeader()};const updateHeader=()=>{$('#headerRank').textContent=store.xp>=500?'じしょマスター':store.xp>=200?'名人見習い':'見習い';$('#headerScore').textContent=(store.xp||0)+' XP'};updateHeader();
const esc=s=>s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const home=()=>{clearInterval(state.timer);state.mode=null;screen.innerHTML=`<section class="hero"><div class="eyebrow">ことばを見つける・くらべる・ならべる</div><h1>じしょマスター</h1><p>国語辞典のひみつを、遊びながら身につけよう。</p></section><section class="mode-grid"><button class="mode-card book" data-action="book"><div class="mode-icon">📖</div><h2>じしょをひこう！</h2><p>「つめ」と「はしら」を使って、ことばを見つけよう！</p><span class="go">ひいてみる →</span></button><button class="mode-card words" data-action="words"><div class="mode-icon">🔤</div><h2>ことばならべ！</h2><p>3つのことばを、じしょに出てくる順にならべよう！</p><span class="go">ならべてみる →</span></button></section><div class="mini-grid"><button class="small-action" data-action="help">？ あそびかた</button><button class="small-action" data-action="records">★ きろく</button><button class="small-action" data-action="weak">にがてれんしゅう</button></div>`};
const header=(title,sub='')=>`<div class="screen-head"><button class="back" data-action="home">← ホーム</button><div><h2>${title}</h2>${sub?`<div class="eyebrow">${sub}</div>`:''}</div><div></div></div>`;
function book(){state.mode='book';state.step=1;state.bookPage=0;renderBook()}
function dict(hot='',first='たから',last='たまご'){return `<div class="dictionary"><div class="dict-page"><div class="dict-header ${hot==='pillar'?'hot':''}"><span>はしら</span><b>${first}　｜　${last}</b><span>はしら</span></div><div class="dict-columns"><div class="dict-column">たいいく</div><div class="dict-column">たから</div><div class="dict-column">たまご</div><div class="dict-column">たんす</div></div>${state.bookPage>=2?'<div class="dict-word">たんぽぽ</div>':''}</div><div class="dict-nail ${hot==='nail'?'hot':''}">つめ　つ　・　て　・　と　・　た</div></div>`}
function renderBook(){let content='';if(state.step===1)content=`<div class="mission">「たんぽぽ」を国語辞典で見つけよう！</div>${dict('')}<div class="hint-box"><p>まず、どこを手がかりにする？</p><div class="choices"><button class="choice" data-book="nail">つめ</button><button class="choice" data-book="pillar">はしら</button><button class="choice" data-book="body">本文</button></div><div class="feedback" id="fb"></div></div>`;if(state.step===2)content=`<div class="mission">「た」は何行？</div>${dict('nail')}<div class="choices">${['あ行','か行','さ行','た行','な行','は行'].map(x=>`<button class="choice" data-row="${x}">${x}</button>`).join('')}</div><div class="feedback" id="fb"></div>`;if(state.step===3)content=`<div class="mission">近くまで来たよ。次はどこを見る？</div>${dict('pillar','たから','たまご')}<div class="hint-box"><div class="choices"><button class="choice" data-pillar="nail">つめ</button><button class="choice" data-pillar="pillar">はしら</button><button class="choice" data-pillar="body">本文</button></div><div class="feedback" id="fb"></div></div>`;if(state.step===4)content=`<div class="mission">「たんぽぽ」は、このページにありそう？</div>${dict('pillar','たから','たまご')}<div class="choices"><button class="choice" data-page="yes">ありそう</button><button class="choice" data-page="no">なさそう</button></div><div class="feedback" id="fb"></div>`;if(state.step===5)content=`<div class="mission">「たんぽぽ」は、このページにありそう？</div>${dict('pillar','たんす','ちから')}<div class="choices"><button class="choice" data-page="yes2">ありそう</button><button class="choice" data-page="no2">なさそう</button></div><div class="feedback" id="fb"></div>`;if(state.step===6)content=`<div class="mission pop">📖 パラパラパラ……</div>${dict('pillar','たんす','ちから')}<div class="compare"><div class="answer-title">✨ たんぽぽ、発見！</div><p>つめで場所をさがして、はしらでページをしぼれたね。</p><button class="primary" data-action="bookClear">次のミッションへ</button></div>`;screen.innerHTML=header('じしょをひこう！','LEVEL '+Math.min(state.step,6))+'<div class="progress"><span style="width:${state.step/6*100}%"></span></div>'+content}
const bookFeedback=(ok,msg,next)=>{const f=$('#fb');f.textContent=msg;f.className='feedback '+(ok?'ok':'no');if(ok)setTimeout(()=>{state.step=next;renderBook()},650)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(a==='home')home();if(a==='help')help();if(a==='records')records();if(a==='weak')weak();if(a==='book')book();if(a==='words')words();if(a==='challenge')challenge();if(a==='bookClear'){store.xp=(store.xp||0)+50;store.bookClear=true;save();home()}if(b.dataset.book)bookFeedback(b.dataset.book==='nail',b.dataset.book==='nail'?'つめ！ ことばの最初の文字を手がかりに、だいたいの場所をさがすよ。':'ここでは「つめ」を見るよ。',2);if(b.dataset.row)bookFeedback(b.dataset.row==='た行',b.dataset.row==='た行'?'た行！ 辞書が「た」の近くまで移動するよ。':'「た」は、た行だね。',3);if(b.dataset.pillar)bookFeedback(b.dataset.pillar==='pillar',b.dataset.pillar==='pillar'?'はしら！ そのページの最初と最後のことばが分かるよ。':'上の「はしら」を見てみよう。',4);if(b.dataset.page)bookFeedback(b.dataset.page==='no',b.dataset.page==='なさそう！ はしらの範囲に「たんぽぽ」はないね。',5);if(b.dataset.page==='yes2')bookFeedback(true,'ありそう！ ページをめくってみよう。',6);if(b.dataset.page==='no2')bookFeedback(false,'はしらを見ると、「たんぽぽ」はこの中にありそう。',5);if(b.dataset.word)state.challenge?pickChallenge(Number(b.dataset.word)):pick(Number(b.dataset.word));if(b.dataset.decide)state.challenge?challengeDecide():decide()});
const pools=[['いぬ','さる','ねこ'],['あさひ','いちご','うさぎ'],['かさ','かに','かめ'],['たこ','たね','たまご'],['はな','はんこ','はね'],['がっこう','かばん','きっぷ'],['きゅうり','きょうしつ','きょだい'],['ケーキ','けしごむ','けんだま'],['ぶどう','ふうせん','ふで'],['まくら','みかん','むし'],['しんぶん','じてんしゃ','しお'],['てぶくろ','でんしゃ','てんき'],['おちゃ','おと','おに'],['すいか','ずこう','すずめ'],['ぱん','はさみ','ばす'],['りんご','らっぱ','るすばん'],['えんぴつ','おうさま','おりがみ'],['くも','くるま','くつ']];
const kanaOrder='ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろわをんー'.split('');const key=w=>[...w].map(x=>kanaOrder.indexOf(x)).map(n=>String(n+100).padStart(3,'0')).join('');
function newWords(){const levelPools=[[0,1],[2,3,4],[5,6],[7,8],[9,10],[11,12],[13,14],[15],[16],[17]];const candidates=levelPools[Math.min(9,Math.max(0,(state.level||1)-1))];const source=pools[candidates[Math.floor(Math.random()*candidates.length)]];state.words=[...source].sort(()=>Math.random()-.5);state.selected=null}
function words(){state.mode='words';state.level=Number(store.wordLevel||1);state.challenge=false;newWords();renderWords()}
function renderWords(){screen.innerHTML=header('ことばならべ！','LEVEL '+state.level)+`<p class="mission">3つのことばを、じしょに出てくる順にならべよう！</p><div class="panel"><div class="word-cards">${state.words.map((w,i)=>`<button class="word-card ${state.selected===i?'selected':''}" data-word="${i}">${esc(w)}</button>`).join('')}</div><p class="center explain">タップで2つを入れかえられるよ。</p><div class="center"><button class="primary gold" data-decide="1">これで決定！</button></div><div id="wordFeedback" class="feedback"></div></div><div class="mini-grid"><button class="small-action" data-action="challenge">⏱ 60秒チャレンジ</button><button class="small-action" data-action="home">ホームへ</button></div>`}
function pick(i){if(state.selected===null){state.selected=i}else if(state.selected!==i){[state.words[state.selected],state.words[i]]=[state.words[i],state.words[state.selected]];state.selected=null}renderWords()}
function pickChallenge(i){if(state.selected===null){state.selected=i}else if(state.selected!==i){[state.words[state.selected],state.words[i]]=[state.words[i],state.words[state.selected]];state.selected=null}renderChallenge()}
function decide(){const good=state.words.every((w,i)=>i===0||key(state.words[i-1])<=key(w));const f=$('#wordFeedback');if(good){store.xp=(store.xp||0)+10;store.wordCorrect=(store.wordCorrect||0)+1;store.wordLevel=Math.min(10,(store.wordLevel||1)+1);save();f.textContent='✨ せいかい！';f.className='feedback ok';setTimeout(()=>renderCompare(),500)}else{store.wordMiss=(store.wordMiss||0)+1;store.weakRule=store.weakRule||'文字のくらべ方';save();f.textContent='おしい！ 前から一文字ずつくらべてみよう。';f.className='feedback no';setTimeout(()=>renderCompare(),550)}}
function renderCompare(){const sorted=[...state.words].sort((a,b)=>key(a).localeCompare(key(b)));screen.innerHTML=header('どこで決まった？','ことばならべ')+`<div class="panel"><div class="compare"><h3>前から一文字ずつ見る</h3><div class="compare-words">${sorted.map((w,i)=>`<div class="compare-word">${[...w].map((c,j)=>j===0?`<mark>${c}</mark>`:c).join('')}</div>`).join('')}</div><p>違う文字が出たところで、五十音順をくらべるよ。</p><strong>${sorted.join(' → ')}</strong></div><div class="center"><button class="primary" data-action="words">もう一問</button><button class="secondary" data-action="home">ホームへ</button></div></div>`}
function challenge(){state.challenge=true;state.time=60;state.correct=0;state.miss=0;state.combo=0;newWords();renderChallenge();state.timer=setInterval(()=>{state.time--;renderChallenge();if(state.time<=0){clearInterval(state.timer);renderResult()}},1000)}
function renderChallenge(){screen.innerHTML=header('60秒チャレンジ','ことばならべ')+`<div class="panel center"><div class="challenge-time">残り ${state.time} 秒　｜　${state.combo} COMBO</div><p class="mission">じしょの順にならべよう！</p><div class="word-cards">${state.words.map((w,i)=>`<button class="word-card ${state.selected===i?'selected':''}" data-word="${i}">${w}</button>`).join('')}</div><button class="primary gold" data-decide="challenge">決定！</button><div class="feedback">正解 ${state.correct}問　まちがい ${state.miss}問</div></div>`}
function challengeDecide(){const good=state.words.every((w,i)=>i===0||key(state.words[i-1])<=key(w));if(good){state.correct++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo)}else{state.miss++;state.combo=0}state.selected=null;newWords();renderChallenge()}
function renderResult(){const total=state.correct+state.miss;const rate=total?Math.round(state.correct/total*100):0;store.best=Math.max(store.best||0,state.correct);save();screen.innerHTML=header('RESULT','60秒チャレンジ')+`<div class="panel records-card center"><div class="stats"><div class="stat"><strong>${state.correct}</strong>正解</div><div class="stat"><strong>${state.miss}</strong>まちがい</div><div class="stat"><strong>${rate}%</strong>正答率</div><div class="stat"><strong>${state.bestCombo}</strong>最高コンボ</div></div><p class="eyebrow">BEST ${store.best||0}問</p><button class="primary" data-action="words">もう一度</button><button class="secondary" data-action="home">ホームへ</button></div>`}
function records(){screen.innerHTML=header('きろく')+`<div class="panel records-card"><div class="stats"><div class="stat"><strong>${store.xp||0}</strong>XP</div><div class="stat"><strong>${store.wordCorrect||0}</strong>正解</div><div class="stat"><strong>${store.best||0}</strong>BEST</div><div class="stat"><strong>${store.bookClear?'1':'0'}</strong>発見</div></div><h3>身についたこと</h3><div class="record-list"><div class="record-item"><strong>📖 辞書をひく</strong>つめ → はしら → 発見</div><div class="record-item"><strong>🔤 ことばを比べる</strong>前から一文字ずつ</div></div></div>`}
function weak(){screen.innerHTML=header('にがてれんしゅう')+`<div class="panel records-card center"><h3>覚えておきたいルール</h3><div class="rule-tags"><span class="tag">${store.weakRule||'まずは一文字目'}</span><span class="tag">同じなら次の文字</span><span class="tag">濁音・半濁音</span><span class="tag">小さい「っ」</span><span class="tag">長音「ー」</span></div><p>まちがえたルールを優先して出題するよ。</p><button class="primary" data-action="words">練習を始める</button></div>`}
function help(){screen.innerHTML=header('あそびかた')+`<div class="panel records-card"><h3>📖 じしょをひこう！</h3><p><b>つめ</b>で、ことばの最初の文字の場所をさがすよ。</p><p><b>はしら</b>で、そのページのことばの範囲をたしかめるよ。</p><hr><h3>🔤 ことばならべ！</h3><p>ことばを前から一文字ずつ見て、同じなら次の文字をくらべよう。</p><p class="center"><button class="primary" data-action="home">わかった！</button></p></div>`}home();
